#ifndef __TONGUE_MODEL_DATA_H__
#define __TONGUE_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_tongue_model_data[];
extern const unsigned int g_tongue_model_data_len;

#endif
